### ISSUE TITLE
Let's move to Mkdocs for easier contribution and integration

### ISSUE THREAD

**Issue by sunya-ch** [sustainable-computing-io/kepler-doc#23]
I found that [Mkdocs](https://www.mkdocs.org) Is easier for contributing in documentation than [Sphinx](https://www.sphinx-doc.org/)  for the following reasons:
- It is based on markdown format which we already use in github page and wiki. So that, we can copy&paste the content that we already put in README or Wiki directly.
- It can serve and see live change in the same theme that will show in github page. 
- CI workflow is already available.  Check https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions

**Comment by rootfs** [comment]
I did a quick google search and find some comparisons between sphinx and mkdocs
- https://news.ycombinator.com/item?id=17717513
- https://github.com/encode/httpx/discussions/1220

**Comment by sunya-ch** [comment]
Additionally, if I understand correctly, even if we use [sphinx-apidoc](https://www.sphinx-doc.org/en/master/man/sphinx-apidoc.html#sphinx-apidoc), it seems to be converted to the ghpage theme anyway which is different from the sphinx but we can see the same live update locally with mkdoc.

I faced the issue before when it looks fine with sphinx locally but show differently on ghpage.
