### ISSUE TITLE
[CNCF Sandbox Onboarding] Track website tasks

### ISSUE THREAD

**Issue by nikimanoledaki** [sustainable-computing-io/kepler-doc#48]
This issue addresses the website tasks from Kepler being onboarded as a Sandbox project.
Main tracking issue: https://github.com/sustainable-computing-io/kepler/issues/698

- [ ] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).
  - [x] CNCF projects are strongly encouraged to host the source of their websites in an open source repository (and under the same organization) so that requests to change can be done via pull requests and the discussions are archived in a transparent manner.
  - [x] It is OK to say that, e.g., “Prometheus was originally created by Soundcloud” or “Kubernetes builds upon 15 years of experience of running production workloads at Google,” but the origin company should not otherwise be referred to on the project homepage.
  - [x] There should be no links or forms for capturing enterprise support leads. Instead, it is fine to have an enterprise support, commercial partners or similar page. Companies must be listed on that page in alphabetical order, or the order can be changed randomly on each page load. It’s OK to have different categories of support offered. Simple vetting by the project is needed to ensure that all companies listed really can provide the support promised. Projects are welcome to outsource this vetting to CNCF staff if it becomes a burden.
  - [x] Links to companies offering support are expected to go a page that at least mentions support of the project. This can either be the company homepage or a project-specific landing page.
  - [x] #52
  - [x] #50
  - [x] #53
- [x] #54

**Comment by husky-parul** [comment]
https://github.com/sustainable-computing-io/kepler-doc/pull/49 closes items

- [x] If there is a copyright notice at the bottom of the page, copyright should be to the project authors or to CNCF, not the origin company. For details, see [Copyright notices](https://github.com/cncf/foundation/blob/main/copyright-notices.md).

- [x]  Website footers must include trademark guidelines by either linking to [Trademark Usage](https://www.linuxfoundation.org/trademark-usage/) (directly or via a "Terms of service" page), or by including the following text: "The Linux Foundation® (TLF) has registered trademarks and uses trademarks. For a list of TLF trademarks, see [Trademark Usage](https://www.linuxfoundation.org/trademark-usage/)".

**Comment by nikimanoledaki** [comment]
Completed by @husky-parul's PRs! Thank you Parul 💚
